"""Adapters for interacting with external systems and the filesystem."""

from econ_paper_cli.adapters.filesystem import (
    ArtifactFileNotFoundError,
    ArtifactNotARegularFileError,
    ChecksumMismatchError,
    FilesystemAdapterError,
    FilesystemPermissionError,
    FilesystemReadError,
    ManifestEncodingError,
    ManifestFileNotFoundError,
    ManifestInvalidJsonError,
    ManifestLoadError,
    ManifestValidationError,
    SizeMismatchError,
    VerificationError,
    VerificationResult,
    load_manifest_from_file,
    verify_artifact,
    verify_local_file,
)

__all__ = [
    "ArtifactFileNotFoundError",
    "ArtifactNotARegularFileError",
    "ChecksumMismatchError",
    "FilesystemAdapterError",
    "FilesystemPermissionError",
    "FilesystemReadError",
    "ManifestEncodingError",
    "ManifestFileNotFoundError",
    "ManifestInvalidJsonError",
    "ManifestLoadError",
    "ManifestValidationError",
    "SizeMismatchError",
    "VerificationError",
    "VerificationResult",
    "load_manifest_from_file",
    "verify_artifact",
    "verify_local_file",
]
