"""Adapters for interacting with external systems and the filesystem."""

from econ_paper_cli.adapters.bm25 import (
    BM25ConfigurationError,
    BM25Retriever,
)
from econ_paper_cli.adapters.corpus import (
    CorpusDomainValidationError,
    CorpusEncodingError,
    CorpusFileNotFoundError,
    CorpusInvalidJsonError,
    CorpusLoadError,
    CorpusNotARegularFileError,
    CorpusPermissionError,
    CorpusReadError,
    load_corpus_from_file,
)
from econ_paper_cli.adapters.filesystem import (
    ArtifactFileNotFoundError,
    ArtifactNotARegularFileError,
    ChecksumMismatchError,
    FilesystemAdapterError,
    FilesystemPermissionError,
    FilesystemReadError,
    InvalidChunkSizeError,
    ManifestEncodingError,
    ManifestFileNotFoundError,
    ManifestInvalidJsonError,
    ManifestLoadError,
    ManifestPermissionError,
    ManifestReadError,
    ManifestValidationError,
    SizeMismatchError,
    VerificationError,
    VerificationPermissionError,
    VerificationReadError,
    VerificationResult,
    load_manifest_from_file,
    verify_artifact,
    verify_local_file,
)

__all__ = [
    "ArtifactFileNotFoundError",
    "ArtifactNotARegularFileError",
    "BM25ConfigurationError",
    "BM25Retriever",
    "ChecksumMismatchError",
    "CorpusDomainValidationError",
    "CorpusEncodingError",
    "CorpusFileNotFoundError",
    "CorpusInvalidJsonError",
    "CorpusLoadError",
    "CorpusNotARegularFileError",
    "CorpusPermissionError",
    "CorpusReadError",
    "FilesystemAdapterError",
    "FilesystemPermissionError",
    "FilesystemReadError",
    "InvalidChunkSizeError",
    "ManifestEncodingError",
    "ManifestFileNotFoundError",
    "ManifestInvalidJsonError",
    "ManifestLoadError",
    "ManifestPermissionError",
    "ManifestReadError",
    "ManifestValidationError",
    "SizeMismatchError",
    "VerificationError",
    "VerificationPermissionError",
    "VerificationReadError",
    "VerificationResult",
    "load_corpus_from_file",
    "load_manifest_from_file",
    "verify_artifact",
    "verify_local_file",
]
