"""Domain types that are independent of infrastructure adapters."""

from econ_paper_cli.domain.artifacts import (
    ArtifactKind,
    ArtifactManifest,
    ArtifactManifestError,
    RedistributionStatus,
)
from econ_paper_cli.domain.citations import Citation
from econ_paper_cli.domain.corpora import Corpus, CorpusValidationError
from econ_paper_cli.domain.errors import (
    CitationValidationError,
    DomainError,
    EvidenceValidationError,
    IngestionEmptyDirectoryError,
    IngestionError,
    IngestionInvalidPathError,
    IngestionPathNotFoundError,
    IngestionPermissionError,
    IngestionReadError,
    IngestionUnsupportedFileError,
    IngestionValidationError,
    PaperValidationError,
    PassageValidationError,
    PDFExtractionValidationError,
    PDFQualityValidationError,
    PDFSectionValidationError,
    ResearchQuestionValidationError,
    SinglePaperAnalysisValidationError,
    StorageRecordValidationError,
)
from econ_paper_cli.domain.evidence import RetrievalEvidence
from econ_paper_cli.domain.ingestion import (
    IngestionPreflightResult,
    PreflightCandidate,
)
from econ_paper_cli.domain.papers import Paper
from econ_paper_cli.domain.passages import Passage
from econ_paper_cli.domain.pdf_extraction import (
    ExtractedPDFPage,
    PDFDocumentMetadata,
    PDFExtractionResult,
)
from econ_paper_cli.domain.pdf_quality import (
    DEFAULT_PDF_QUALITY_SETTINGS,
    PDFExtractionQualityAssessment,
    PDFPageQualityObservation,
    PDFQualityMeasurements,
    PDFQualitySettings,
    PDFQualityStatus,
    PDFQualityWarning,
    PDFQualityWarningCode,
)
from econ_paper_cli.domain.pdf_sections import (
    DEFAULT_PDF_SECTION_SETTINGS,
    PDFHeadingCandidate,
    PDFSection,
    PDFSectionDetectionResult,
    PDFSectionKind,
    PDFSectionSettings,
    PDFSectionSpan,
    PDFSectionWarning,
    PDFSectionWarningCode,
)
from econ_paper_cli.domain.research_question import (
    DEFAULT_RESEARCH_QUESTION_SETTINGS,
    ResearchQuestionEvidence,
    ResearchQuestionKind,
    ResearchQuestionResult,
    ResearchQuestionSettings,
    ResearchQuestionWarning,
    ResearchQuestionWarningCode,
)
from econ_paper_cli.domain.single_paper_analysis import (
    DEFAULT_SINGLE_PAPER_ANALYSIS_SETTINGS,
    SinglePaperAnalysisResult,
    SinglePaperAnalysisSettings,
    SinglePaperAnalysisStage,
    SinglePaperAnalysisStatus,
    SinglePaperAnalysisWarning,
    SinglePaperAnalysisWarningCode,
)
from econ_paper_cli.domain.storage import (
    ConversionSettings,
    IngestionCompletion,
    IngestionWarning,
    PaperRecord,
    SourceProvenance,
)

__all__ = [
    "ArtifactKind",
    "ArtifactManifest",
    "ArtifactManifestError",
    "Citation",
    "CitationValidationError",
    "ConversionSettings",
    "Corpus",
    "CorpusValidationError",
    "DomainError",
    "EvidenceValidationError",
    "ExtractedPDFPage",
    "IngestionCompletion",
    "IngestionEmptyDirectoryError",
    "IngestionError",
    "IngestionInvalidPathError",
    "IngestionPathNotFoundError",
    "IngestionPermissionError",
    "IngestionPreflightResult",
    "IngestionReadError",
    "IngestionUnsupportedFileError",
    "IngestionValidationError",
    "IngestionWarning",
    "Paper",
    "PaperRecord",
    "PaperValidationError",
    "Passage",
    "PassageValidationError",
    "PDFDocumentMetadata",
    "PDFExtractionResult",
    "PDFExtractionValidationError",
    "PDFExtractionQualityAssessment",
    "PDFPageQualityObservation",
    "PDFQualityMeasurements",
    "PDFQualitySettings",
    "PDFQualityStatus",
    "PDFQualityValidationError",
    "PDFQualityWarning",
    "PDFQualityWarningCode",
    "DEFAULT_PDF_QUALITY_SETTINGS",
    "PDFHeadingCandidate",
    "PDFSection",
    "PDFSectionDetectionResult",
    "PDFSectionKind",
    "PDFSectionSettings",
    "PDFSectionSpan",
    "PDFSectionValidationError",
    "PDFSectionWarning",
    "PDFSectionWarningCode",
    "DEFAULT_PDF_SECTION_SETTINGS",
    "PreflightCandidate",
    "RedistributionStatus",
    "ResearchQuestionEvidence",
    "ResearchQuestionKind",
    "ResearchQuestionResult",
    "ResearchQuestionSettings",
    "ResearchQuestionValidationError",
    "ResearchQuestionWarning",
    "ResearchQuestionWarningCode",
    "DEFAULT_RESEARCH_QUESTION_SETTINGS",
    "SinglePaperAnalysisResult",
    "SinglePaperAnalysisSettings",
    "SinglePaperAnalysisStage",
    "SinglePaperAnalysisStatus",
    "SinglePaperAnalysisValidationError",
    "SinglePaperAnalysisWarning",
    "SinglePaperAnalysisWarningCode",
    "DEFAULT_SINGLE_PAPER_ANALYSIS_SETTINGS",
    "RetrievalEvidence",
    "SourceProvenance",
    "StorageRecordValidationError",
]
